name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: compress
      bash tar -xzf shibboleth-embedded-ds-patched.1.2.2.tar.gz shibboleth-embedded-ds-patched.1.2.2

    - uses: actions/upload-artifact@v3
      with:
        path: shibboleth-embedded-ds-patched.1.2.2.tar.gz