name: Publish pkg

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: bash build_gitlab.sh

      - name: show
        run: pwd && ls -l

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shibboleth-embedded-ds-patched-1.2.2.tar.gz
            shibboleth-embedded-ds-patched-1.2.2.tar.gz.sha256