name: Publish

on:
  push:
    branches:
      - main
      - new_patch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: bash build.sh

      - name: show
        run: pwd && ls -l

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
